// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GyOewz83aEpWsyEoZkLlGnGCcH2t5s4',
    appId: '1:298296892134:web:696f3fce9a8729c1dbf927',
    messagingSenderId: '298296892134',
    projectId: 'newday-b915e',
    authDomain: 'newday-b915e.firebaseapp.com',
    storageBucket: 'newday-b915e.firebasestorage.app',
    measurementId: 'G-HWE6B7L40T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIEzX4nRqORp9F-dMedpQ1St6cITbfcw',
    appId: '1:298296892134:android:a1d81b72c85c7ebedbf927',
    messagingSenderId: '298296892134',
    projectId: 'newday-b915e',
    storageBucket: 'newday-b915e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwihoDDTLutwNpXmgEhrwTT-GTzfU-qM',
    appId: '1:298296892134:ios:beed0fbb89a9dd65dbf927',
    messagingSenderId: '298296892134',
    projectId: 'newday-b915e',
    storageBucket: 'newday-b915e.firebasestorage.app',
    iosBundleId: 'com.dogu.newDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwihoDDTLutwNpXmgEhrwTT-GTzfU-qM',
    appId: '1:298296892134:ios:beed0fbb89a9dd65dbf927',
    messagingSenderId: '298296892134',
    projectId: 'newday-b915e',
    storageBucket: 'newday-b915e.firebasestorage.app',
    iosBundleId: 'com.dogu.newDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8GyOewz83aEpWsyEoZkLlGnGCcH2t5s4',
    appId: '1:298296892134:web:7d7a3295dcc8fb79dbf927',
    messagingSenderId: '298296892134',
    projectId: 'newday-b915e',
    authDomain: 'newday-b915e.firebaseapp.com',
    storageBucket: 'newday-b915e.firebasestorage.app',
    measurementId: 'G-LT75RYB6WM',
  );
}
